server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /sw.js {
        add_header Cache-Control "no-cache";
        add_header Service-Worker-Allowed "/";
        try_files $uri =404;
    }

    location /manifest.json {
        add_header Cache-Control "no-cache";
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
